# Generated by Django 5.2.6 on 2025-12-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_farmer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='password',
            field=models.CharField(blank=True, help_text='Store raw password for linking to User', max_length=128, null=True),
        ),
    ]
