# Generated by Django 5.2.6 on 2026-02-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_farmer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_selfies/'),
        ),
    ]
