# Generated by Django 5.2.6 on 2025-12-11 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_supply', models.BooleanField(default=False, help_text='Check if this category is for supply products (tools, fertilizer, etc)')),
            ],
        ),
        migrations.AlterField(
            model_name='produce',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_supply': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.productcategory'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_supply': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.productcategory'),
        ),
    ]
