# Generated by Django 5.2.6 on 2026-02-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_produce_seller_supplyproduct_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='produce_images/'),
        ),
        migrations.AddField(
            model_name='produce',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='produce_images/'),
        ),
        migrations.AddField(
            model_name='supplyproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='supply_images/'),
        ),
        migrations.AddField(
            model_name='supplyproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='supply_images/'),
        ),
    ]
