# Generated by Django 5.2.6 on 2025-12-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('field_officer', 'Field Officer'), ('seller', 'Seller'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
