# Generated by Django 5.2.6 on 2025-12-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_tag', models.CharField(help_text='RFID Tag Number', max_length=50, unique=True)),
                ('animal_type', models.CharField(choices=[('cattle', 'Cattle'), ('buffalo', 'Buffalo'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('pig', 'Pig'), ('poultry', 'Poultry'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, help_text='Optional animal name', max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age_months', models.PositiveIntegerField(help_text='Age in months')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Current weight in kg', max_digits=6)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('under_treatment', 'Under Treatment'), ('quarantined', 'Quarantined'), ('deceased', 'Deceased')], default='healthy', max_length=20)),
                ('last_vaccination_date', models.DateField(blank=True, null=True)),
                ('last_checkup_date', models.DateField(blank=True, null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=200, null=True)),
                ('pen_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_rfid', models.CharField(blank=True, help_text="Mother's RFID tag", max_length=50, null=True)),
                ('father_rfid', models.CharField(blank=True, help_text="Father's RFID tag", max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'ordering': ['-registered_date'],
            },
        ),
        migrations.CreateModel(
            name='AnimalHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('checkup', 'Routine Checkup'), ('treatment', 'Treatment'), ('surgery', 'Surgery'), ('injury', 'Injury'), ('disease', 'Disease'), ('other', 'Other')], max_length=20)),
                ('record_date', models.DateField()),
                ('veterinarian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_given', models.TextField(blank=True, null=True)),
                ('medication', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'ordering': ['-record_date'],
            },
        ),
    ]
